### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Give the page a background color
- [x] Add an image of a car in the center of the page
- [x] Size the car appropriately
